# This file will be included by the Makefile under the project directory.

FLOAT_OBJ := $(FLOAT:.a=.o)

$(FLOAT): $(FLOAT_OBJ)
	ar r $(FLOAT) $(FLOAT_OBJ)

# TODO: write a rule for generating $(FLOAT_OBJ)

vpath %.h lib-common
vpath %.c lib-common

obj/lib-common/FLOAT.o : FLOAT.h FLOAT.c
	mkdir obj/lib-common; cd lib-common; cc -c -m32 -fno-builtin FLOAT.h FLOAT.c
	mv lib-common/FLOAT.o obj/lib-common
